Remove deprecated files and update project structure for Homebridge plugin. Deleted ESLint configuration, license, nodemon configuration, TypeScript configuration, and accessory implementations. Updated package.json with new dependencies and changed project name to @home-bridge-plugin/source. Adjusted GitHub Actions workflow for Node.js version 22.x and switched to pnpm for package management.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,29 +10,32 @@ jobs:
       fail-fast: false
       matrix:
         # the Node.js versions to build on
-        node-version: [18.x, 20.x]
+        node-version: [22.x]
 
     steps:
       - uses: actions/checkout@v3
 
-      - name: Use Node.js ${{ matrix.node-version }} 
+      - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
 
       - name: Install dependencies
-        run: npm install
+        run: pnpm install
 
       - name: Lint the project
-        run: npm run lint
+        run: pnpm nx run-many -t lint
 
       - name: Build the project
-        run: npm run build
+        run: pnpm nx run-many -t build
 
       - name: List, audit, fix outdated dependencies and build again
         run: |
           npm list --outdated
-          npm audit || true  # ignore failures
-          npm audit fix || true
+          pnpm audit || true  # ignore failures
+          pnpm audit fix || true
           npm list --outdated
-          npm run build
+          pnpm nx run-many -t build
+
+      - name: Publish to npm
+        run: pnpm nx run-many -t nx-release-publish
